version: "{build}"

os: Windows Server 2012 R2

clone_folder: c:\gopath\src\github.com\aybabtme\godotto

environment:
  GOPATH: c:\gopath

install:
  - echo %CD%
  - echo %PATH%
  - echo %GOPATH%
  - go version
  - go env
  - go get github.com/Masterminds/glide
  - c:\gopath\bin\glide -v

build_script:
  - c:\gopath\bin\glide install
  - go test -v -cover ./cmd/... ./internal/... ./pkg/...
  - go build ./cmd/...
